# Generated by Django 4.1 on 2022-08-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='title',
        ),
    ]
