version: "3.9"
services:
  web:
    platform: linux/amd64
    build: .
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
    - db
    - rabbit
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: db/Dockerfile
    image: postgres:latest
    volumes:
    - ./data/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
  celery:
    platform: linux/amd64
    restart: always
    build:
     context: .
    command: celery -A blog worker -l info
    volumes:
    - .:/code
    environment:
    - DB_HOST=db
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASS=postgres
    depends_on:
    - db
    - rabbit
    - web
  rabbit:
    platform: linux/amd64
    image: rabbitmq:latest
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    ports:
    - "5672:5672"