# Generated by Django 3.2 on 2022-08-21 16:32

from django.db import migrations, models
import utils.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mail', models.CharField(max_length=320, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.CheckAgeMixin),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', utils.fields.HTMLField()),
                ('template', models.FileField(blank=True, null=True, upload_to='mails/templates/')),
                ('plain_text', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128)),
                ('recipents', models.ManyToManyField(related_name='mails', to='mails.Newsletter')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.CheckAgeMixin),
        ),
    ]
