# Generated by Django 3.2 on 2022-09-01 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0002_rename_recipents_mail_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='recipients',
        ),
        migrations.AddField(
            model_name='mail',
            name='newsletters',
            field=models.ManyToManyField(null=True, related_name='mails', to='mails.Newsletter'),
        ),
        migrations.AddField(
            model_name='mail',
            name='users',
            field=models.ManyToManyField(null=True, related_name='mails', to=settings.AUTH_USER_MODEL),
        ),
    ]
